### ISSUE TITLE
File is being used by other process

### ISSUE THREAD

**Issue by iquasere** [mzdb/pwiz-mzdb#68]
Greetings

I have used raw2mzDB successfully in the past with real data in .wiff format. Now I am trying to run simulated data (mzML format) on raw2mzDB, but I get the error message
```
W1220 10:08:02.399674  8524 mzdb_writer.hpp:236] Metadata extraction is not supported for this file format:mzML format
I1220 10:08:02.400674  8524 mzdb_writer.cpp:1051] DDA / DIA test
I1220 10:08:02.437670  8524 mzdb_writer.cpp:1056] DDA Mode detected
I1220 10:08:02.437670  8524 raw2mzDB.cpp:611]

************ Summary of the parameters ************

Treating file: MSSim/two_proteins.mzML (DDA mzML format)
MS 1    Selected Mode: FITTED
MS 2    Selected Mode: CENTROID

Bounding box dimensions:
MS 1    m/z: 5 Da, retention time: 15sec
MS n    m/z: 10000 Da, retention time: 0sec

I1220 10:08:02.438912  8524 mzdb_writer.hpp:352]
I1220 10:08:02.439915  8524 mzdb_writer.hpp:353] SQLITE VERSION: 3.8.9
I1220 10:08:02.440915  8524 mzdb_writer.hpp:354] ProteoWizard release: 3.0.7320 (2015-3-18)
I1220 10:08:02.441915  8524 mzdb_writer.hpp:355] ProteoWizard MSData: 3.0.7303 (2015-3-13)
I1220 10:08:02.443915  8524 mzdb_writer.cpp:97] Settings SQLite pragmas...
I1220 10:08:02.444926  8524 mzdb_writer.cpp:121] Create database tables...
I1220 10:08:02.455934  8524 mzdb_writer.cpp:743] use default source file
E1220 10:08:02.456917  8524 mzdb_writer.hpp:374] Unknown error during metadata insertion.
I1220 10:08:02.457916  8524 mzdb_writer.hpp:390] SpectrumList size: 501
I1220 10:08:02.458912  8524 mzdb_writer.hpp:412] #detected core(s): 4
I1220 10:08:02.461913  8524 mzdb_writer.hpp:515] Default spectrumList
I1220 10:08:02.464912  8524 mzdb_writer.hpp:523] DDA producer/consumer
I1220 10:08:02.471931  5528 peak_finder_wavelet.hpp:97] ABU scan=1 rt=500 mzs.size=335 centroids=335
I1220 10:08:03.466756  8524 mzdb_writer.hpp:536] Creating permanent spectrum table
I1220 10:08:03.471758  8524 mzdb_writer.cpp:368] Creates indexes...
I1220 10:08:03.503751  8524 spectrum_inserter.h:599]

************ Summary of the conversion ************

Created file: MSSim/two_proteins.mzML.mzDB
MS      Input           Output          Nb spectra
MS1     CENTROID        CENTROID        501


I1220 10:08:03.504750  8524 raw2mzDB.cpp:635] Checking run slices numbers
I1220 10:08:03.508750  8524 mzdb_writer.cpp:1013] Detected problem in run slice number...fixing it
E1220 10:08:03.517751  8524 raw2mzDB.cpp:645] boost::filesystem::rename: The process couldn't access the file because it is being used by another process: "MSSim/two_proteins.mzML.mzDB.tmp", "MSSim/two_proteins.mzML.mzDB"
I1220 10:08:03.518751  8524 raw2mzDB.cpp:652] Elapsed Time: 1.08 sec
```
But I have just booted the computer, so the file being already in use is not the problem! Is this a known bug? I have also validated the files against schema version 1.1.0, and they all came back valid.

**Comment by AlexandreBurel** [comment]
Hi João,

During the process, the file is given the extension 'mzDB.tmp' and at the end it's extension is renamed into 'mzDB'.

Your error happens when the "rename" functions fail. So it means the file is either opened, moved or deleted (or any other reason that would make it not accessible anymore by the converter). It's a new file so it should not be already in use before the conversion. Also, it's the very last step of the conversion, so if it hasn't fail before the file should be valid and at the right place.

Everytime this error happened to me, it was because I opened the file too early to check if it was ok. That's why I added the ".tmp" extension by the way :p. But I doubt that you tried that and forgot to mention it in your issue...

Is your error reproducible ?
If it just happened once and you don't want to run the converter again, you can just rename the mzDB.tmp file into mzDB, it should work just fine.

**Comment by iquasere** [comment]
It is reproducible on my system, as it happens with all simulated mzML files.  But only on these files, it worked completely fine on my WIFF raw data. I think I can send you the file this way:
[two_proteins.mzML.txt](https://github.com/mzdb/pwiz-mzdb/files/3987973/two_proteins.mzML.txt)

**Comment by AlexandreBurel** [comment]
I get the same error, but not on others mzML files. That's strange !
I'll try to have a look when I have a moment but it's very likely that it will not be in 2019 :p

**Comment by iquasere** [comment]
Ahahah if you can't look at this before, I hope you have a nice Christmas and New Year! And thank you for all the help, your tools have been very useful!

**Comment by iquasere** [comment]
Trying to open the .tmp files as .mzDB is not working, but does not exit with error code. Simply never ends :(

**Comment by AlexandreBurel** [comment]
The real problem is probably because the simulated mzML files are not well recognized, and the consequences are what you describe.
Also, it finds only MS1 centroid spectra. I don't think it should be a problem but I've never had such case so it's typically a case that hasn't been tested so far...

But holidays are almost there so I'm not going to start working on that now 😄 
Merry Christmas to you too, and happy new year !

**Comment by iquasere** [comment]
Although loading through a jupyter notebook the .tmp file didn't work, through the CLI it did. My simulated files have no MS1 nor MS2 events, and that probably messes with raw2mzdb.

**Comment by iquasere** [comment]
I was using safeMode, dunno if it could have made a difference. The tool wouldn't work without that.
